### ISSUE TITLE
Compose work contract

### ISSUE THREAD

**Issue by carlosnasillo** [latticemarkets/employee-handbook#1]
@peterhunn, The [Employee Agreement](https://guides.github.com/features/mastering-markdown/) needs to be written up. 

We need to keep several considerations in place such as clauses around when things kick into place prior to fund raise, terminations, probation periods, non-competes etc, etc.

**Comment by peterhunn** [comment]
Are we contracting as an employee or on a service contract basis? There are obviously different legal, tax and financial ramifications.

**Comment by carlosnasillo** [comment]
For the time being we are going down the freelancer route (purely because we don't have the structure in place to hire perms). That being said, unless stated otherwise we would see them as perm until their transition happens for when we have funding / structure.

**Comment by peterhunn** [comment]
Thats the best route, but wasn't aware. In which case we need a separate section for freelancers + a contract for service (not employment). We can say that it is a temp contract with a view to a permanent position but we need to hire for a set period of time in the first instance.

**Comment by carlosnasillo** [comment]
Sounds good
