### ISSUE TITLE
Verify the IP employee agreement

### ISSUE THREAD

**Issue by carlosnasillo** [latticemarkets/employee-handbook#2]
@peterhunn, the [Intellectual Property agreement](https://github.com/latticemarkets/employee-handbook/blob/master/Hiring%20Documents/Employee%20Proprietary%20Information%20and%20Inventions%20Assignment%20Agreement.md) was pulled from the web. 

Could you please verify this is comprehensive and do any amendments if required.

**Comment by peterhunn** [comment]
This is US. I will spin up a UK agreement.

**Comment by carlosnasillo** [comment]
:+1:
